### ISSUE TITLE
User can view a list of movies

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/toplist-project#1]
## ⚙️ Feature
User can view a list of movies with posters and some information 

## 📐 Functionality
User can view a list of movies with description and IMDb rating.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-08-01 at 9 47 37 AM](https://user-images.githubusercontent.com/106217355/182204276-374aed5f-34a7-457d-b27e-71e75bbec086.png)

![Screen Shot 2022-08-01 at 10 06 55 AM](https://user-images.githubusercontent.com/106217355/182204393-2976be00-21c6-48aa-8271-758ce4562e37.png)

## ✅ Task List

- [x] Create HTML file
- [x] Add all CSS styling necessary
- [x] Ensure that it looks nice on both mobile-sized and desktop-sized screens.
- [x] Add a div[data-view="list-movies"] to the HTML.
- [x] Add some movies info to the list in the HTML and style them to match the wireframe.
- [x] Create a new XMLHttpRequest object
- [x] For each movie object in the response, create necessary elements and append it to the page 
  - [x]  Define a function that takes a single movie object and returns a DOM tree that matches one of the example entries in the HTML.
  - [x] Use a loop to create a DOM tree for each movie and append it to the page when the 'DOMContentLoaded' event is fired.
  - [x] Remove the example HTML once the movies are successfully being appended to the DOM on page load.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all functionality works without errors.
