### ISSUE TITLE
User can see detailed information about a single movie.

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/toplist-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see detailed information about a single movie.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Display the detailed information about a movie.
User can see it by clicking on More Details.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-01 at 10 13 34 AM](https://user-images.githubusercontent.com/106217355/182205360-aed2aeff-14f2-45b9-b861-716f08bd6357.png)

![Screen Shot 2022-08-01 at 10 14 09 AM](https://user-images.githubusercontent.com/106217355/182205440-4e0fe3c0-8b4d-46d4-9e16-e89df9e2f983.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add a sibling div[data-view="more-details"] to the HTML.
- [x] Add button element and listen for click
- [x] Add all CSS styling necessary
- [x] Ensure that by clicking on button more details div[data-view="list-movies"] is hidden 
- [x] Create another request for different api 
- [x] Using loop find the movie was clicked (by the title/id)
- [x] Append data to the page
- [x] Add an anchor to the main page view that shows the list of movies
- [x] Ensure that by clicking on an anchor list of all movies is shown
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
