### ISSUE TITLE
User can add a movie to their watch list.

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/toplist-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a movie to their watch list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The watch list will save all the movies, user choose to add to the list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-01 at 10 16 55 AM](https://user-images.githubusercontent.com/106217355/182205902-50687329-2351-4e00-b16f-1ed4f81fd9c6.png)

![Screen Shot 2022-08-01 at 10 17 25 AM](https://user-images.githubusercontent.com/106217355/182205944-8dc81cdd-3883-4615-b9bb-0c8627a72ea3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update rendering function to include a button for each movie.
- [x] Listen for clicks on button
- [x] Create a new movie object as user clicks on add to watchlist button 
- [x] Create a data model to store a movie that user chooses to add to their list
- [x] Prepend the new object to the data model.
- [x] Verify that 'movies' are saved to local storage along with the rest of the data model on page reload.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
