### ISSUE TITLE
User can see the full list of their added movies.

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/toplist-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the full list of their added movies.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can see the full list of their added movies in the Watchlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-01 at 10 19 50 AM](https://user-images.githubusercontent.com/106217355/182206458-726882cf-e101-47d7-acb0-a00fb8ea703f.png)

![Screen Shot 2022-08-01 at 10 19 18 AM](https://user-images.githubusercontent.com/106217355/182206381-c0b390b6-bae7-4242-98c6-baffb4f9e690.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling div[data-view="watchlist"] to the HTML.
- [x] Add an anchor to the main page that shows Watchlist
- [x] Ensure that by clicking on an anchor Watchlist is shown
- [x] Append necessary data to the page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
