### ISSUE TITLE
User can remove a movie from watchlist.

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/toplist-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove a movie from watchlist.

If a user saw a movie or decides that they no longer wish to keep it in a list, they should be able to delete it.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allow users to delete a movie from watchlist screen.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-01 at 10 23 11 AM](https://user-images.githubusercontent.com/106217355/182206873-ff2c15b1-d3d8-44b2-a77c-654b9217510f.png)

![Screen Shot 2022-08-01 at 10 23 39 AM](https://user-images.githubusercontent.com/106217355/182206974-1180ee88-4bbe-41ec-b303-177256bd739c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Add a click target for deleting a movie that only appears if the user is clicks 'more details' in theirs watchlist
- [x] Show a confirmation modal when the user clicks the Delete button.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the movie object from the data model and the movie DOM tree from the page if the user clicks Delete.
- [x] Show the Watchlist if the user clicks Delete.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
